sudo: required
dist: trusty
language: cpp
os:
- linux
compiler:
  - gcc
cache:
  directories:
  - "$BUILD_DIR/aws"
addons:
   apt:
      packages:
      - zlib1g-dev
      - libbz2-dev
      - libsnappy-dev
      - curl
      - libgflags-dev
      - mingw-w64
      - libcurl4-openssl-dev
      - libssl-dev
      - uuid-dev
      - libpulse-dev
env:
  - TEST_GROUP=db_test
  - TEST_GROUP=db_test2
  - TEST_GROUP=cloud_tests

before_script:
  # Increase the maximum number of open file descriptors, since some tests use
  # more FDs than the default limit.
  - ulimit -n 8192
  - wget https://github.com/aws/aws-sdk-cpp/archive/1.3.50.tar.gz -O /tmp/aws-sdk.tar.gz && tar -xvf /tmp/aws-sdk.tar.gz > /dev/null
  - pushd aws-sdk-cpp-1.3.50 && cmake -DBUILD_ONLY="s3;kinesis" . && make -j4 all && sudo make install && popd

script:
  - if [ "${TEST_GROUP}" == 'db_test' ]; then OPT=-DTRAVIS V=1 USE_AWS=1 make -j4 db_test && LD_LIBRARY_PATH=/usr/local/lib ./db_test; fi
  - if [ "${TEST_GROUP}" == 'db_test2' ]; then OPT=-DTRAVIS V=1 USE_AWS=1 make -j4 db_test2 && LD_LIBRARY_PATH=/usr/local/lib ./db_test2; fi
  - if [ "${TEST_GROUP}" == 'cloud_tests' ]; then OPT=-DTRAVIS V=1 USE_AWS=1 make -j4 db_cloud_test cloud_manifest_test && LD_LIBRARY_PATH=/usr/local/lib ./db_cloud_test && LD_LIBRARY_PATH=/usr/local/lib ./cloud_manifest_test; fi

notifications:
  slack:
    rooms:
      secure: uq/N3oixvz9hwX1VeLAFsXb5P7DnMk7eZIhzoSgsVWP/pVL26YPRzLamKUwUOCTW8HStQ20FHIjwidNuj28OaOS1maOAgJzG2SEgaer/LkbhmEwpKD4ik4Wqd5CKIDAZRYiVWe3PS1UYPGn7Ys0X9zsyewnPTMN6adwZr3PxiJUKl0Ce5jq35P7n+IYnklsJMoczj7yH/nssu7B0lgRcZrDl29JCYe8OaJZVOoBnmBJB/x1p9tHVGZo247yrYd2OTeR1ISFPWDiq0rQyFgTqXiLoq0ZyLO/DRLozegc39ljwcjQ5eiKOaQkwbHMWDc968Y/TsAQcSccMT80juIIdw2bVN3zPthMHosw/v9YyWGVPztFDyHIh2UcxfV/T2fGZN2pSMQ1g7yYYqla2qTOGXBGkIa4c0QqxukQhwZ3wV2Wx2cFhK/oOT+xtVqoW4vy20f1bbbcUoLR0lLxZRk902g1jot72z1NwdGGsCtH6x097xHs+M2PfB2Dt4ICaAqsI+NR1s1hmfaQ4G8PuYSzuT2j3fIDRMbioeutfxMGJSYQ/R3w0ue7rjYecIDh3H+OGk5HSjD1nO1LV3UTWm5MPfsZcfwwGbSe2KMUtftghsSKRNg9WiUzApnZdrj5IdSoOw/A6Jgm29DEPJCtQDO8okU7oE+4lBuUh34PwMIQ+zfw=
    on_success: always
    on_failure: always
